=== gschizas/profoga/AminoAcids.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by George Schizas (TerraSoft) -->
<!--W3C Schema generated by XMLSPY v2004 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="aminoacid">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="atoms"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="ALA"/>
						<xs:enumeration value="ARG"/>
						<xs:enumeration value="ASN"/>
						<xs:enumeration value="ASP"/>
						<xs:enumeration value="CYS"/>
						<xs:enumeration value="GLN"/>
						<xs:enumeration value="GLU"/>
						<xs:enumeration value="GLY"/>
						<xs:enumeration value="HIS"/>
						<xs:enumeration value="ILE"/>
						<xs:enumeration value="LEU"/>
						<xs:enumeration value="LYS"/>
						<xs:enumeration value="MET"/>
						<xs:enumeration value="PHE"/>
						<xs:enumeration value="PRO"/>
						<xs:enumeration value="SER"/>
						<xs:enumeration value="THR"/>
						<xs:enumeration value="TRP"/>
						<xs:enumeration value="TYR"/>
						<xs:enumeration value="VAL"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="aminoacids">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="aminoacid" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="atom">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="C"/>
						<xs:enumeration value="H"/>
						<xs:enumeration value="N"/>
						<xs:enumeration value="O"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="id" type="xs:integer" use="optional"/>
			<xs:attribute name="x" type="xs:float" use="required"/>
			<xs:attribute name="y" type="xs:float" use="required"/>
			<xs:attribute name="z" type="xs:float" use="required"/>
			<xs:attribute name="charge" type="xs:string" use="optional"/>
			<xs:attribute name="dehydrate" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="C"/>
						<xs:enumeration value="N"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="atoms">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="atom" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="link">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="bond">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="Single"/>
								<xs:enumeration value="Double"/>
								<xs:enumeration value="Triple"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gschizas/profoga/AminoAcids.xml
<?xml version="1.0"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by George Schizas (TerraSoft) -->
<aminoacids xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\GSchizas\My Documents\Biotech\DISS\ProFoGA.NET\AminoAcids.xsd">
	<aminoacid name="ALA">
		<atoms>
			<atom name="C" id="1" x="0" y="0" z="0" charge=" ">
				<link>2</link>
				<link>6</link>
				<link>9</link>
				<link>13</link>
			</atom>
			<atom name="C" id="2" x="-1.22324" y="-0.73875" z="-0.47522">
				<link>1</link>
				<link bond="2">3</link>
				<link>4</link>
			</atom>
			<atom name="O" id="3" x="-2.29002" y="-0.15931" z="-0.60055">
				<link bond="2">2</link>
			</atom>
			<atom name="O" id="4" x="-1.16815" y="-2.03140" z="-0.68167" dehydrate="C">
				<link>2</link>
				<link>5</link>
			</atom>
			<atom name="H" id="5" x="-0.28602" y="-2.34131" z="-0.51273" dehydrate="C">
				<link>4</link>
			</atom>
			<atom name="N" id="6" x="1.20765" y="-0.69724" z="-0.46791">
				<link>1</link>
				<link>7</link>
				<link>8</link>
			</atom>
			<atom name="H" id="7" x="1.79438" y="-0.03919" z="-1.01939" dehydrate="N">
				<link>6</link>
			</atom>
			<atom name="H" id="8" x="0.93259" y="-1.50131" z="-1.06777">
				<link>6</link>
			</atom>
			<atom name="C" id="9" x="0.03447" y="1.44390" z="-0.48943">
				<link>1</link>
				<link>10</link>
				<link>11</link>
				<link>12</link>
			</atom>
			<atom name="H" id="10" x="-0.77029" y="1.62313" z="-1.21731">
				<link>9</link>
			</atom>
			<atom name="H" id="11" x="1.00327" y="1.65098" z="-0.96789">
				<link>9</link>
			</atom>
			<atom name="H" id="12" x="-0.09586" y="2.12028" z="0.36808">
				<link>9</link>
			</atom>
			<atom name="H" id="13" x="-0.00000" y="0.00000" z="1.09985">
				<link>1</link>
			</atom>
		</atoms>
	</aminoacid>
	<aminoacid name="ARG">
		<atoms>
			<atom name="C" id="1" x="0.00000" y="0.00000" z="0.00000">
				<link>2</link>
				<link>6</link>
				<link>8</link>
				<link>10</link>
			</atom>
			<atom name="C" id="2" x="-1.25839" y="-0.70029" z="-0.49537"/>
			<atom name="O" id="3" x="-2.45166" y="-0.00912" z="0.01482"/>
			<atom name="O" id="4" x="-1.29215" y="-0.72429" z="-1.96553"/>
			<atom name="H" id="5" x="-1.29979" y="-1.62474" z="-2.26759"/>
			<atom name="N" id="6" x="1.17737" y="-0.73918" z="-0.47981"/>
			<atom name="H" id="7" x="1.73708" y="-1.06448" z="0.33430"/>
			<atom name="H" id="8" x="-0.00000" y="0.00000" z="1.09995"/>
			<atom name="H" id="9" x="0.86723" y="-1.56059" z="-1.03721"/>
			<atom name="C" id="10" x="0.04345" y="1.43903" z="-0.49888"/>
			<atom name="C" id="11" x="1.29630" y="2.13931" z="0.00679"/>
			<atom name="C" id="12" x="1.22259" y="3.62180" z="-0.32187"/>
			<atom name="N" id="13" x="2.36977" y="4.30252" z="0.24863"/>
			<atom name="C" id="14" x="2.50288" y="5.70025" z="0.05653"/>
			<atom name="N" id="15" x="3.57685" y="6.39290" z="0.66570"/>
			<atom name="N" id="16" x="1.56981" y="6.41190" z="-0.73665"/>
			<atom name="H" id="17" x="0.81034" y="5.92761" z="-1.17054"/>
			<atom name="H" id="18" x="1.67286" y="7.39823" z="-0.86508"/>
			<atom name="H" id="19" x="3.67333" y="7.37976" z="0.53590"/>
			<atom name="H" id="20" x="4.23441" y="5.89641" z="1.23243"/>
			<atom name="H" id="21" x="0.04201" y="1.44890" z="-1.59883"/>
			<atom name="H" id="22" x="-0.84315" y="1.97519" z="-0.12949"/>
			<atom name="H" id="23" x="2.18152" y="1.70250" z="-0.47757"/>
			<atom name="H" id="24" x="1.37434" y="2.01146" z="1.09659"/>
			<atom name="H" id="25" x="1.22067" y="3.75434" z="-1.41398"/>
			<atom name="H" id="26" x="0.29985" y="4.04620" z="0.10099"/>
			<atom name="H" id="27" x="3.02995" y="3.80203" z="0.80885"/>
		</atoms>
	</aminoacid>
	<aminoacid name="ASN">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="ASP">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="CYS">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="GLN">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="GLU">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="GLY">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="HIS">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="ILE">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="LEU">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="LYS">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="MET">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="PHE">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="PRO">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="SER">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="THR">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="TRP">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="TYR">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
	<aminoacid name="VAL">
		<atoms>
			<atom name="C" id="0" x="" y="" z=""/>
		</atoms>
	</aminoacid>
</aminoacids>
